# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{.Branch}}-{{ checksum "package.json" }}
            - v1-dependencies-{{.Branch}}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - ~/cache
          key: v1-dependencies-{{.Branch}}-{{ checksum "package.json" }}

      # run tests!
      - run: yarn build
      - run: yarn test:unit --coverage
      - run: yarn test:e2e-ci
      - store_artifacts:
          path: /artifacts/e2e/video
      - store_test_results:
          path: ./coverage
        
